version: "3.9"

services:
  app:
    build: .
    env_file:
      - .env
    container_name: apollonft
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apollonft.rule=Host(`apollonft.io`)"
      - "traefik.http.routers.apollonft.entrypoints=websecure"
      - "traefik.http.routers.apollonft.tls=true"
      - "traefik.http.routers.apollonft.tls.certresolver=myresolver"
    networks:
      - traefik
    ports:
      - "3000:3000" # optional if using Traefik only

networks:
  traefik:
    external: true
